name: Bug Report
description: Report a problem or regression
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue. Please provide as much detail as possible.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect to happen?
      placeholder: Briefly describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide versions and runtime details.
      placeholder: |
        - Flotilla version:
        - Server deployment target (Docker, bare metal, etc.):
        - Agent platform(s):
        - Browser (if UI-related):
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs & Diagnostics
      description: Include relevant logs, stack traces, screenshots, or metrics.
      render: shell
*** End Patch

